#!/bin/sh

file=$1
GENFILES=$2

# Create the code files; both in the output document format and as an independent file (if applicable)
count=0
CODEBLOCK=N # Global variable to determine whether or not we have a code block in the file; if Y, then \usepackage[dvipsnames]{xcolor}
a='```'
ptrn="${a}@C@?[a-z]*@?[a-z]*"

CODESRCFILES="$(grep -E "${ptrn}" "${file}" | cut -d"@" -f4 | sort -u)"

[ -n "$CODESRCFILES" ] && {
	for srcf in $CODESRCFILES
	do
		rm -v "$srcf"
	done
}

sed -E -n "/^${ptrn}/=" "${file}" | awk '{if (NR % 2 == 0) { print $1 } else { printf $1 "," }}' | while read -r LINE
do
	start=${LINE%%,*}
	end=${LINE##*,}
	lang=$(sed -n "${start}p" "${file}" | cut -d'@' -f3)
	[ -n "$(sed -n "${start}p" "${file}" | cut -d'@' -f4)" ] && langfile="$(sed -n "${start}p" "${file}" | cut -d'@' -f4)" || langfile=""
	tl="${count}-code-${file}.tmp.${lang}"
	sed -n "${start},${end}p" "${file}" > "$tl"
	sed -E -i "/$ptrn/d" "$tl"
	[ -n "$langfile" ] && cat "$tl" >> "$langfile"
	source-highlight --src-lang "${lang}" --out-format latexcolor -o "${count}-code-${file}.tex" -i "$tl"
	rm "$tl"
	CODEBLOCK=Y
	sed "${start},${end}s/.*/@input@${count}-code-${file}.tex@/g" "copy-${file}" > "copy-${count}-${file}"
	mv "copy-${count}-${file}" "copy-${file}"
	echo "${count}-code-${file}.tex" >> "$GENFILES"
	count=$((count + 1))
done
